### ISSUE TITLE
output file significantly larger than input

### ISSUE THREAD

**Issue by great-thoughts** [xanguera/BeamformIt#9] opened 2016-07-18 09:31 UTC
My original audio files had a size of  154MB, however, beamformit produces an output of 617MB. the fileSize = (bitsPerSample \* samplesPerSecond \* channels \* duration) / 8;
How can I make beamformit write the output file with the same settings and not change the size of the processed audio.

**Comment by xanguera** [comment] 2016-07-18 09:47
Can you give me some more information about your input files? what format are they in?

**Comment by great-thoughts** [comment] 2016-07-18 09:54
they are wav

**Comment by great-thoughts** [comment] 2016-07-18 10:16
do you face a similar issue if you run beamformit on any of your audios?

**Comment by xanguera** [comment] 2016-07-18 10:33
This is strange. Generally you should get an output file with roughly the same size as any one of the input files. can you run "soxi" on one of your files and paste here the result? also do the same for the beamformit result.

**Comment by great-thoughts** [comment] 2016-07-18 11:06
This is for one of the input file:
Input File     : 'test1.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 01:24:12.48 = 80839680 samples ~ 378936 CDDA sectors
File Size      : 162M
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM

This is after beamforit:
Input File     : 'finaltest.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 53-bit
Duration       : 01:24:14.34 = 80869376 samples ~ 379075 CDDA sectors
File Size      : 647M
Bit Rate       : 1.02M
Sample Encoding: 64-bit Floating Point PCM

**Comment by xanguera** [comment] 2016-07-18 11:24
The problem is clearly coming from the sample encoding. 
Beamformit uses floaring point values to internally encode the audio samples. Unless you set the parameter "output_format" to 3 (default is 0) it should convert them to your input format before printing out.
Are you running the script do_beamformig.sh?
I am not able to reproduce your problem (my output files are exactly the same size as the input) so I can not help much for now. Until we find the issue, you could use sox on the output to force 16bit/sample...

**Comment by great-thoughts** [comment] 2016-07-18 12:08
yes I am running do_beamforming. using sox in this way fixes the issue

**Comment by xanguera** [comment] 2016-07-19 11:33
Closing this issue as I can not reproduce it locally and there seems to be a temporary solution to it.

**Closed as completed by xanguera** 2016-07-19 11:33 UTC
